feat:nvm

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,4 +27,12 @@ jobs:
 
       - name: test node
         run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} `
-          source ~/.bashrc && nvm -v`
+          export NVM_DIR="$HOME/.nvm"
+          if[ -s "$NVM_DIR/nvm.sh" ]; then
+          . "$NVM_DIR/nvm.sh"
+          else
+          echo "nvm.sh not found"
+          exit 1
+          fi
+
+          nvm -v`
