feat:node

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,19 +25,19 @@ jobs:
       - name: Add SSH known hosts
         run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
-      # - name: test node
-      #  run: |
-      #    ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} `
-      #    export NVM_DIR="$HOME/.nvm"
-      #    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
-      #    echo "nvm.sh not found"
-      #    exit 1
-      #    }
+      - name: test node
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+          export NVM_DIR="$HOME/.nvm"
+          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
+          echo "nvm.sh not found"
+          exit 1
+          }
 
-      #    nvm -v
-      #    nvm use --lts
-      #    node -v
-      #    npm -v`
+          nvm -v
+          nvm use --lts
+          node -v
+          npm -v'
 
       - name: check mysql
         run: |
